version: "3.9"
x-default-logging: &logging
   driver: "json-file"
   options:
     max-size: "10m"
     max-file: "2"

x-default-deploy-resources: &deploy-resources
  resources:
    limits:
      cpus: "0.2"
      memory: 128M
    reservations:
      cpus: "0.1"
      memory: 64M

services:
  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - "${GRAFANA_SERVICE_PORT}-3002:${GRAFANA_SERVICE_PORT}"
    depends_on:
      prometheus:
        condition: service_healthy
    logging: *logging
    deploy:
      mode: replicated
      replicas: 2
      << : *deploy-resources
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://${GRAFANA_ADDR}/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s

  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./config/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      - prometheus_data:/prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://${PROMETHEUS_ADDR}/-/healthy || exit 1
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    deploy: *deploy-resources
    ports:
      - "${PROMETHEUS_SERVICE_PORT}:${PROMETHEUS_SERVICE_PORT}"
    logging: *logging

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100"
    volumes:
      - loki_data:/loki
    deploy: *deploy-resources

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./config/loki/promtail-config.yaml:/etc/promtail/config.yml
      # Read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    deploy: *deploy-resources

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - "${CADVISOR_SERVICE_PORT}:${CADVISOR_SERVICE_PORT}"
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--docker_only=true"
      - "--housekeeping_interval=30s"
      - "--disable_metrics=cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp"
    deploy: *deploy-resources

networks:
  default:
    name: observability

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
