{
 "title": "Daemon Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers per state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"docker\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage - RSS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"docker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_bucket{action=\"create\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Start",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_bucket{action=\"start\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}