{
 "title": "Loki stack monitoring (Promtail, Loki)",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "tags": [
  "tools",
  "loki"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Problems in the Loki Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of error messages logged by Loki itself",
   "type": "timeseries",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total{level=~\"error|warn\"}[1m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "{container=\"observability-loki-1\"} | logfmt | level = `error`"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "graph",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total{instance=\"promtail:9080\",level=~\"error|warn\"}[1m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "{container=\"observability-promtail-1\"} | logfmt | level = `error`"
    }
   ]
  },
  {
   "title": "Promtail - dropped log entries",
   "type": "timeseries",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[1m])*60",
     "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
    }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Streams in Loki",
   "type": "timeseries",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "timeseries",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "timeseries",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  }
 ]
}